name: Windows Build
on:
  push:
    branches: [main]
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          - run: npm install
      - run: npm run dist
      - uses: actions/upload-artifact@v4
        with:
          name: Customify-Windows-Installer
          path: dist/*.exe
